branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/github'
    - - '@semantic-release/exec'
      - prepareCmd: "cargo install cargo-bump && cargo bump ${nextRelease.version}"
        publishCmd: "make publish"
    - - '@semantic-release/git'
      - assets: Cargo.toml